migrate vesting contracts
LlamaPay/interface pull request #104
Opened 2024-03-30 15:53 UTC by mintdart

2024-05-04 19:23 UTC, 0xngmi requested changes

2024-05-04 19:23 UTC, 0xngmi commented on components/Vesting/Table/CustomValues/Migrate.tsx
> +          // TODO update it to networkDetails[chainId].vestingFactory
is this todo wrong?

2024-05-05 04:25 UTC, mintdart commented on components/Stream/Table/CustomValues/TotalStreamed.tsx
> +        if (ref.current) {
it shouldn't be, removed it

2024-05-05 04:29 UTC, mintdart commented on components/Vesting/create/index.tsx
> -      setRecipient(recipientAddress);
setting it here in handleChange https://github.com/LlamaPay/interface/pull/104/files/4dd9166dc3f1f55c428b940b3ed025aa68b597c2#diff-7f608adae12abf7a4ebeecbe2dbaef68c48b28136ce07859d06790466c7ae5a2R168 , if we set recipient inside onSubmit , can't show `Recipient can't be same as the funder warning` here https://github.com/LlamaPay/interface/pull/104/files/4dd9166dc3f1f55c428b940b3ed025aa68b597c2#diff-7f608adae12abf7a4ebeecbe2dbaef68c48b28136ce07859d06790466c7ae5a2R171

2024-05-05 04:30 UTC, mintdart commented on components/Vesting/Table/CustomValues/Migrate.tsx
> +          // TODO update it to networkDetails[chainId].vestingFactory
yes, removed it

2024-05-05 13:47 UTC, merged